//! Regenerates ui/css/syntax.css from syntect themes.
//! Run: cargo run --example gen_syntax_css > ../ui/css/syntax.css
use syntect::highlighting::ThemeSet;
use syntect::html::{css_for_theme_with_class_style, ClassStyle};

fn scoped(css: &str, scope: &str) -> String {
    css.lines()
        .map(|l| {
            if l.starts_with('.') {
                l.split(", ").map(|s| format!("{scope} {s}")).collect::<Vec<_>>().join(", ")
            } else {
                l.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn main() {
    let themes = two_face::theme::extra();
    let defaults = ThemeSet::load_defaults();
    let light = &defaults.themes["InspiredGitHub"];
    let dark = themes.get(two_face::theme::EmbeddedThemeName::OneHalfDark);
    let style = ClassStyle::SpacedPrefixed { prefix: "hl-" };
    let mut l = css_for_theme_with_class_style(light, style).unwrap();
    let mut d = css_for_theme_with_class_style(dark, style).unwrap();
    // Background is owned by markdown.css.
    for css in [&mut l, &mut d] {
        *css = css.lines().filter(|x| !x.trim_start().starts_with("background-color")).collect::<Vec<_>>().join("\n");
    }
    println!("/* Generated by src-tauri/examples/gen_syntax_css.rs — do not edit by hand. */");
    println!("{}", scoped(&l, ":root:not([data-theme=\"dark\"])"));
    println!("{}", scoped(&d, ":root[data-theme=\"dark\"]"));
}
